name: resuse workflow 
on:
   workflow_dispatch:
jobs:
  reuseable:
    name: reuseablefile
    runs-on: ubuntu-latest
    steps:
      - name: creating docker container
        run: docker pull httpd
      - name: verify image
        run: dokcer images
      - name: creating a container
        run: docker run -itd --name apache2 -p 8080:80 httpd